name: Metrics
on:
  # Schedule updates
  schedule: 
  - cron: "0 * * * *"
  # Lines below let you run workflow manually and on each commit
  push: 
    branches: "main"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: Asia/Seoul
          plugin_languages: yes
          plugin_languages_ignored: ""
          plugin_languages_skipped: ""
          plugin_stars: yes
          plugin_stars_limit: 4          
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_followup: yes
